services:
  yt_bot:
    container_name: deltachat_yt_bot
    build: .
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./data:/app/data
      - ./data/ytbot:/root/.config/ytbot
    environment:
      - DC_DB_DIR=/app/data
      - DB_PATH=/app/data/ytbot.db
      - ALLOWED_BOT_EMAILS=${ALLOWED_BOT_EMAILS:-}
      - PROXY=${PROXY:-}
      - YANDEX_PROXY=${YANDEX_PROXY:-}
      - YANDEX_TOKEN=${YANDEX_TOKEN:-}
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
